### ISSUE TITLE
Test rollback-altboot (broken init)

### ISSUE THREAD

**Issue by resinio** [balena-os/balena-os#547] opened 2019-11-26 16:17 UTC
# Description 
Note: *The OLD OS must be v2.30+*

rollback-altboot recovers the device if the new OS after a HUP never reaches balenaOS prompt.

# Steps to reproduce issue 
Make sure you are running the old OS on the device. Not the new OS.

#### 1 Run HUP

`hostapp-update -i <DOCKERHUB_ACCOUNT>/<DOCKERHUB_REPO>:<TAG>`

Note: This is without the -r flag. We don't want to reboot the device. We would like to mess up the new OS before rebooting.

#### 2 Break new OS in inactive partition (break init)

`rm /mnt/sysroot/inactive/current/boot/init`

#### 3 Reboot

`reboot`

# Expected result 
If you have a dev version of the device and serial plugged in, you should see the kernel serial output, then a hang/reboot. then uboot will print a message switching to previous rootfs (grub gives no message). 

You'll see the previous OS boot. However, after a minute or so (depending on the device), the device will reboot again.

Then the OS will properly boot into the previous OS. 

Check `cat /etc/os-release` to confirm you are on the previous OS.
Check `ls /mnt/state` for a flag file `rollback-altboot-triggered`.

# Other information 
- Reported by: Florin Sarbu 

- Test configuration: CTI Orbitty TX2 

- Test case number: TC45 

- Test run: [https://resinio.testlodge.com/projects/16238/runs/478116?tab=2&run_section_id=689952#executed_case_20195303](https://resinio.testlodge.com/projects/16238/runs/478116?tab=2&run_section_id=689952#executed_case_20195303)

**Comment by acostach** [comment] 2019-11-26 16:47
This ticket is a duplicate of https://github.com/balena-os/balena-jetson/issues/17 . It was raised by testlodge in the meta-balena repository because the right tickbox was probably missed. @floion - closing it here and handling the issue in the original ticket.

**Closed by acostach** 2019-11-26 16:47 UTC
